trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: '6.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetToolInstaller@0
  displayName: 'Installing Nuget Tools...'
  inputs:
    versionSpec: '4.9.2'

- script: dotnet build --configuration $(buildConfiguration) src/Blazored.Toast/Blazored.Toast.csproj
  displayName: 'Building $(buildConfiguration)...'

- task: DotNetCoreCLI@2
  displayName: 'Generating Nuget Package... '
  inputs:
    command: pack

    arguments: --no-build
    packagesToPack: src/Blazored.Toast/Blazored.Toast.csproj
    configuration: $(buildConfiguration)

- task: PublishBuildArtifacts@1
  displayName: 'Publishing Build Artifacts...'