//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedComponents.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Transition {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Transition() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedComponents.Resources.Transition", typeof(Transition).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   .{0} {{
        ///    animation: none;
        ///    transition: opacity 500ms, transform 500ms;
        ///    opacity: 0;
        ///  }}
        ///
        ///  .{0}.blazored-toast-open {{
        ///    opacity: 1;
        ///  }}
        ///
        ///  .{0}.blazored-toast-closing {{
        ///    opacity: 1;
        ///    transform: scale(0);
        ///  }}.
        /// </summary>
        public static string FadeInScaleOutTransitionCss {
            get {
                return ResourceManager.GetString("FadeInScaleOutTransitionCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   .{0} {{
        ///    animation: none;
        ///    transition: opacity 500ms;
        ///    opacity: 0;
        ///  }}
        ///
        ///  .{0}.blazored-toast-open {{
        ///    opacity: 1;
        ///  }}.
        /// </summary>
        public static string FadeTransitionCss {
            get {
                return ResourceManager.GetString("FadeTransitionCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   .{0} {{
        ///    animation: none;
        ///    transition: transform 500ms;
        ///    transform: scale(0);
        ///  }}
        ///
        ///  .{0}.blazored-toast-open {{
        ///    transform: scale(1);
        ///  }}.
        /// </summary>
        public static string ScaleTransitionCss {
            get {
                return ResourceManager.GetString("ScaleTransitionCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   .blazored-toast-container.position-topleft .{0},
        ///  .blazored-toast-container.position-bottomleft .{0} {{
        ///    animation: none;
        ///    transition: right 500ms;
        ///    right: 110%;
        ///  }}
        ///
        ///  .blazored-toast-container.position-topleft .{0}.blazored-toast-open,
        ///  .blazored-toast-container.position-bottomleft .{0}.blazored-toast-open {{
        ///    right: 0;
        ///  }}
        ///
        ///  .blazored-toast-container.position-topright .{0},
        ///  .blazored-toast-container.position-bottomright .{0} {{
        ///    animation: none;
        ///    transition: left [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SlideTransitionCss {
            get {
                return ResourceManager.GetString("SlideTransitionCss", resourceCulture);
            }
        }
    }
}
